pulseaudio --start
while true; do
  sleep 1
  pactl set-card-profile alsa_card.pci-0000_00_1b.0 output:hdmi-stereo
done &
echo $! > ~/.pactl_loop.pid
xrandr --output LVDS-1 --off
if test 12 -eq $(date +%m); then
  # Merry Christmas.
  mplayer -loop 0 -rootwin -volume 0 .christmas_video.mp4
else
  xscreensaver -nosplash
fi &
exec i3
