---
- include:              '../tasks/user_groups.yml'
- include:              '../tasks/users.yml'
- include:              '../tasks/add_users_to_groups.yml'
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/create_files.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/lines_in_files.yml'
- include:              '../tasks/reboot.yml'
  when:                 user_groups_result.changed
                        or users_result.changed
                        or add_users_to_groups_result.changed
                        or install_packages_result.changed
                        or create_files_result.changed
                        or install_files_result.changed
                        or lines_in_files_result.changed
