---
- include_tasks:        '../tasks/user_groups.yml'
- include_tasks:        '../tasks/users.yml'
- include_tasks:        '../tasks/add_users_to_groups.yml'
- include_tasks:        '../tasks/remove_packages.yml'
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/adjust_files.yml'
- include_tasks:        '../tasks/create_files.yml'
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/lines_in_files.yml'
- include_tasks:        '../tasks/reboot.yml'
  when:                 user_groups_result.changed
                        or users_result.changed
                        or add_users_to_groups_result.changed
                        or remove_packages_result.changed
                        or install_packages_result.changed
                        or adjust_files_result.changed
                        or create_files_result.changed
                        or install_files_result.changed
                        or lines_in_files_result.changed
