---
- include:              '../tasks/user_groups.yml'
- include:              '../tasks/users.yml'
- include:              '../tasks/add_users_to_groups.yml'
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/create_files.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/lines_not_in_files.yml'
- include:              '../tasks/lines_in_files.yml'
